// Public surface of @csf/platform (the DOM-free core). Svelte components are
// published separately via the "./ui/*" subpath exports so this barrel — and
// `tsc` over it — never touches a.svelte file.

export {
  AssessmentMetaSchema,
  AssessmentSchema,
  AssessmentTargetSchema,
  AnswerSchema,
  DimensionSchema,
  DimensionQuestionSchema,
  DimensionStratumTargetSchema,
  DimensionTargetSchema,
  DraftWorkbookSchema,
  GestureSchema,
  HorizonSchema,
  AnswerLedgerRecordSchema,
  AnswerSnapshotSchema,
  ClashChoiceSchema,
  ClashClassSchema,
  ClashResolutionSchema,
  EstateBaseSchema,
  LandingEnvelopeSchema,
  LandingSchema,
  LedgerCandidateSchema,
  LedgerDecisionSchema,
  LedgerRecordSchema,
  MaterialitySchema,
  ObjectiveSchema,
  PartyChoiceSchema,
  PartyDecisionSchema,
  PartyLedgerRecordSchema,
  PartyRecordDecisionSchema,
  ParticipantSchema,
  PartyKindSchema,
  PartyQuestionSchema,
  PartySchema,
  PartyTargetSchema,
  PartyTypeSchema,
  ClaimSchema,
  QuestionSchema,
  RecommendationLinkSchema,
  RecommendationSchema,
  RecommenderSchema,
  RoleDefSchema,
  RungSchema,
  SealLevelSchema,
  SealSchema,
  TargetSchema,
  TargetRewriteSchema,
  TestEstateAnswerSchema,
  TestEstateSchema,
  WorkbookAssessmentMetaSchema,
  WorkbookAssessmentSchema,
  WorkbookMetaSchema,
  WorkbookSchema,
} from './schema';
export type {
  Answer,
  AnswerLedgerRecord,
  AnswerSnapshot,
  Assessment,
  AssessmentMeta,
  Claim,
  ClashChoice,
  ClashClass,
  ClashResolution,
  Dimension,
  DimensionQuestion,
  DimensionStratumTarget,
  DimensionTarget,
  EstateBase,
  Gesture,
  Horizon,
  Landing,
  LandingEnvelope,
  LedgerCandidate,
  LedgerDecision,
  LedgerRecord,
  Materiality,
  Objective,
  Participant,
  Party,
  PartyChoice,
  PartyDecision,
  PartyKind,
  PartyLedgerRecord,
  PartyQuestion,
  PartyRecordDecision,
  PartyType,
  Question,
  Recommendation,
  RecommendationLink,
  Recommender,
  Role,
  RoleDef,
  Rung,
  Seal,
  SealLevel,
  Target,
  TargetRewrite,
  TestEstate,
  TestEstateAnswer,
  Workbook,
  WorkbookAssessment,
  WorkbookAssessmentMeta,
  WorkbookMeta,
} from './schema';
export { issuesUnder } from './schema';

export {
  answerFor,
  applicableDimensionsOf,
  applicableParties,
  applyPlacement,
  assessmentOf,
  attainablePoints,
  AUTHOR_QA_PROVENANCE,
  addedProviderFrom,
  bindingPotential,
  checkAssessmentIntegrity,
  claimCompleteness,
  claimCoversQuestion,
  claimCoversUnit,
  claimVisibleDimensions,
  claimVisibleParties,
  claimWalk,
  defaultParties,
  estateCoverage,
  findAnswer,
  fullWalk,
  mergeStrata,
  nextGroupId,
  partyClaimed,
  placeGroupParty,
  placeIndividualParty,
  questionCoverage,
  questionCoverageDetail,
  questionUnits,
  rungAtPosition,
  rungIn,
  rungOf,
  scopeCompleteness,
  sealOfAnswer,
  setAnswer,
  setAnswers,
  sliceHygiene,
  splitDimensionsOf,
  strataOf,
  targetKey,
} from './assessment';
export type { AnswerValue, AssessmentProvenance, BindingPotential, EstateCoverage, PartyPlacement, IntegrityResult, LadderChoice, Placement, QuestionCoverage, QuestionCoverageDetail, ScopeCompleteness, SliceHygiene, WalkSection } from './assessment';

export {
  DEFAULT_PARTY_COUNT,
  DUPLICATE_PAIR_CAP,
  DUPLICATE_WARN_THRESHOLD,
  HEDGED_QUANTIFIERS,
  MINUTES_EXTRA_UNIT,
  MINUTES_FIRST_UNIT,
  MINUTES_TARGET,
  NO_ESTATES_REASON,
  QUESTION_TARGET,
  addDimension,
  addObjective,
  addParty,
  addQuestion,
  addRole,
  addTestEstate,
  authorGauges,
  clearEstateAnswer,
  duplicateRadar,
  estateAnswers,
  estateFloorFlips,
  evaluateTestEstate,
  jaccard,
  ladderLint,
  nextId,
  questionTokens,
  questionsUsingRole,
  recommendationReadout,
  removeDimension,
  removeObjective,
  removeParty,
  removeQuestion,
  removeRole,
  removeTestEstate,
  setAssessedParty,
  setAxis,
  setEstateAnswer,
  setFrontSheet,
  setGrain,
  addRung,
  updateRung,
  removeRung,
  moveRung,
  setStrata,
  setWorkbookMeta,
  starterWorkbook,
  testEstateReadings,
  toggleAppliesTo,
  updateDimension,
  updateObjective,
  updateParty,
  updateQuestion,
  updateRole,
  updateTestEstate,
} from './author';
export type {
  AuthorGauges,
  BudgetGauge,
  CoverageCell,
  CoverageGauge,
  DuplicateWarning,
  EstateFiring,
  EstateFloorFlip,
  GateEntry,
  GateVia,
  LintFinding,
  QuestionLint,
  ReadoutRecommendation,
  RecommendationReadout,
  RoleLoad,
  RoleReadout,
  TestEstateEvaluation,
  TestEstateReading,
} from './author';

export { checkWorkbookAssessmentIntegrity, workbookAssessmentOf } from './setup';
export type { WorkbookAssessmentParts } from './setup';

export {
  NO_HISTORY_VIEW,
  applyOutcomes,
  authorityLabel,
  authorityOf,
  candidateProvenance,
  checkPartial,
  choiceKey,
  clashCandidates,
  classify,
  describeTarget,
  effectOf,
  finalizeLanded,
  isClash,
  isHistoryView,
  land,
  landingChecks,
  landingOutcomes,
  landingRefusalMessage,
  landingSummary,
  ledgerUnits,
  optionsFor,
  reanswerCells,
  recordSentence,
  resolveClash,
  reviewLanding,
  reviewSummary,
  sameHistoryView,
  sameStanding,
  shortLandingId,
  snapshotOf,
  standingCandidate,
  suggest,
  suggestedChoice,
  unitHistory,
  upsertPartyDecision,
  upsertResolution,
} from './merge';
export type {
  AgreedUnit,
  CandidateProvenance,
  ClashOption,
  ClashUnitOutcome,
  FloorBinding,
  FloorPreview,
  GrainClash,
  GrainStratum,
  HistoryView,
  LandingChecks,
  LandingClash,
  LandingDecisions,
  LandingEffect,
  LandingOutcome,
  LandingRefusal,
  LandingReview,
  LandingStamp,
  LandingSummary,
  LandingUnit,
  LedgerUnit,
  PartialCheck,
  RecordRef,
  ReanswerCell,
  ReviewCandidate,
  ReviewSummary,
  SoleSourceUnit,
  SuggestedChoice,
  Suggestion,
  SuggestionBasis,
  UnitClash,
  UnitHistoryEntry,
  UnitOutcome,
  Viewer,
} from './merge';

export { SECTION_ORDER, SECTION_TITLE, TILE_IDS, isTileId } from './analytics';
export type { TileDef, TileId, TileSection, TileWidth } from './analytics';

export { NOT_A_CERTIFICATION, reportDocument, reportFilename } from './report';
export type {
  ReportCover,
  ReportDocument,
  ReportReading,
  ReportSection,
  ReportStamp,
} from './report';

export { decideLoad } from './load';
export type { LoadMode, LoadOutcome, LoadInput, ConfirmCopy } from './load';

export { evaluate } from './score-engine';
export type {
  Credibility,
  DeclaredDimension,
  DeclaredParty,
  EngineResult,
  EvidenceCoverage,
  ExposureEdge,
  FloorHole,
  HeatCell,
  HeatFact,
  ObjectiveResult,
  OpenUnit,
  OverallResult,
  StaircaseBinding,
  StaircaseStep,
  StratumCell,
  UnitCoverage,
} from './score-engine';

export { answerLabel, rungLabel } from './utils/answer-label';
export { cn } from './utils/cn';
export { sealSwatchClass } from './utils/seal-color';
export { provenanceLensClass } from './utils/provenance-lens';
